package cn.jbolt.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("companybusiness", "CompanyId", Companybusiness.class);
		arp.addMapping("deals", "DealID", Deals.class);
		// Composite Primary Key order: CompanyId,FinancialAuditors
		arp.addMapping("financialauditors", "CompanyId,FinancialAuditors", Financialauditors.class);
		// Composite Primary Key order: CompanyId,JobTitle,KeyExecutives
		arp.addMapping("keyexecutive", "CompanyId,JobTitle,KeyExecutives", Keyexecutive.class);
		// Composite Primary Key order: id2,﻿id1
		arp.addMapping("relation", "id2,﻿id1", Relation.class);
	}
}

