package cn.jbolt.common.model;

import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;

import cn.jbolt.common.model.base.BaseCompanybusiness;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Companybusiness extends BaseCompanybusiness<Companybusiness> {
	public static final Companybusiness dao = new Companybusiness().dao();
	
	public Page<Record> findByCompanyName(int page,String CompanyName){
		return Db.paginate(page,9, "select *","from companybusiness where CompanyName like '%"+CompanyName+"%'");
	}
	public List<Record> findByCompanyName(String name){//企业关系
		return Db.find( "select CompanyId,Companyname,JobTitle,KeyExecutives from keyexecutive NATURAL JOIN companybusiness where CompanyName='"+name+"'");
	}
	public List<Record> findExecutiveByCompanyName(String name1,String name2){//企业关系查公司
		return Db.find("select distinct KeyExecutives,JobTitle from keyexecutive NATURAL JOIN companybusiness where (CompanyName='"+name1+"' or CompanyName='"+name2+"')and KeyExecutives in (select KeyExecutives from keyexecutive NATURAL JOIN companybusiness where (CompanyName='"+name1+"' or CompanyName='"+name2+"') group by KeyExecutives HAVING COUNT(KeyExecutives)>1)");
	}
	public Page<Record> findByExecutiveName(int page,String HumanName){//查人
		return Db.paginate(page,10, "select *","from companybusiness natural join keyexecutive"
				+ " where KeyExecutives like '%"+HumanName+"%'");
	}
	public Record findall(String CompanyName){
		return Db.findFirst("select * from companybusiness where CompanyName='"+CompanyName+"'");
	}
	public Page<Record> findBySimilarIndustry(int page,String Industry){
		return Db.paginate(page,9, "select *","from companybusiness where Industry='"+Industry+"'");
	}
	public Page<Record> findBySameExecutives(int page,String keyexecutive){//查相似高管
		return Db.paginate(page,9, "select *","from keyexecutive,companybusiness where KeyExecutives='"+keyexecutive+"' and keyexecutive.CompanyId=companybusiness.CompanyId");
	}
	public Page<Record> findExecutives(int page,int CompanyId){
		return Db.paginate(page,9, "select *","from keyexecutive where CompanyId="+CompanyId);
	}
}
