package cn.jbolt.common.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;

import cn.jbolt.common.model.base.BaseCompanybusiness;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Companybusiness extends BaseCompanybusiness<Companybusiness> {
	public static final Companybusiness dao = new Companybusiness().dao();
	
	public Page<Record> findByCompanyName(int page,String CompanyName){
		return Db.paginate(page,9, "select *","from companybusiness where CompanyName like '%"+CompanyName+"%'");
	}
	public Page<Record> findByExecutiveName(int page,String HumanName){//查人
		return Db.paginate(page,10, "select *","from companybusiness natural join keyexecutive"
				+ " where KeyExecutives like '%"+HumanName+"%'");
	}
	public Record findall(String CompanyName){
		return Db.findFirst("select * from companybusiness where CompanyName='"+CompanyName+"'");
	}
	public Page<Record> findBySimilarIndustry(int page,String Industry){
		return Db.paginate(page,9, "select *","from companybusiness where Industry='"+Industry+"'");
	}
	public Page<Record> findBySameExecutives(int page,String CompanyName,String[] executive,String[] auditor){//查相似高管
		String sql="from companybusiness where KeyExecutives like '%"+executive[1]+"%'";
		for(int i=2;i<executive.length;i++){
			if(!executive[i].equals("n/a")){
				sql+=" or KeyExecutives like '%"+executive[i]+"%'";
			}
			
		}
		for(int i=0;i<auditor.length;i++){
			if(!auditor[i].equals("n/a")){
				sql+=" or FinancialAuditors like '%"+auditor[i]+"%'";
			}
			
		}
		sql+=" and CompanyName!='"+CompanyName+"'";
		return Db.paginate(page,9, "select *",sql);
		
	}
}
