package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseDeals;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Deals extends BaseDeals<Deals> {
	public static final Deals dao = new Deals().dao();
}
