package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseFinancialauditors;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Financialauditors extends BaseFinancialauditors<Financialauditors> {
	public static final Financialauditors dao = new Financialauditors().dao();
}
