package cn.jbolt.common.model;

import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;

import cn.jbolt.common.model.base.BaseKeyexecutive;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Keyexecutive extends BaseKeyexecutive<Keyexecutive> {
	public static final Keyexecutive dao = new Keyexecutive().dao();
	public List<Record> findByExecutiveName(int id){//查高管
		return Db.find( "select * from keyexecutive where companyid= "+id+" order by jobtitle desc");
	}
}
