package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Relation extends BaseRelation<Relation> {
	public static final Relation dao = new Relation().dao();
}
