package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFinancialauditors<M extends BaseFinancialauditors<M>> extends Model<M> implements IBean {

	public M setCompanyId(java.lang.Integer CompanyId) {
		set("CompanyId", CompanyId);
		return (M)this;
	}
	
	public java.lang.Integer getCompanyId() {
		return getInt("CompanyId");
	}

	public M setFinancialAuditors(java.lang.String FinancialAuditors) {
		set("FinancialAuditors", FinancialAuditors);
		return (M)this;
	}
	
	public java.lang.String getFinancialAuditors() {
		return getStr("FinancialAuditors");
	}

}
