package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRelation<M extends BaseRelation<M>> extends Model<M> implements IBean {

	public M setId1(java.lang.String Id1){
		set("﻿Id1", Id1);
		return (M)this;
	}
	
	public java.lang.String get﻿Id1() {
		return getStr("﻿Id1");
	}

	public M setId2(java.lang.String Id2) {
		set("Id2", Id2);
		return (M)this;
	}
	
	public java.lang.String getId2() {
		return getStr("Id2");
	}

	public M setWeight(java.lang.String weight) {
		set("weight", weight);
		return (M)this;
	}
	
	public java.lang.String getWeight() {
		return getStr("weight");
	}

}
