package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDeals<M extends BaseDeals<M>> extends Model<M> implements IBean {

	public M setDealID(java.lang.String DealID) {
		set("DealID", DealID);
		return (M)this;
	}
	
	public java.lang.String getDealID() {
		return getStr("DealID");
	}

	public M setDate(java.lang.String Date) {
		set("Date", Date);
		return (M)this;
	}
	
	public java.lang.String getDate() {
		return getStr("Date");
	}

	public M setCountryOfTarget(java.lang.String CountryOfTarget) {
		set("CountryOfTarget", CountryOfTarget);
		return (M)this;
	}
	
	public java.lang.String getCountryOfTarget() {
		return getStr("CountryOfTarget");
	}

	public M setTargetCompany(java.lang.String TargetCompany) {
		set("TargetCompany", TargetCompany);
		return (M)this;
	}
	
	public java.lang.String getTargetCompany() {
		return getStr("TargetCompany");
	}

	public M setDealType(java.lang.String DealType) {
		set("DealType", DealType);
		return (M)this;
	}
	
	public java.lang.String getDealType() {
		return getStr("DealType");
	}

	public M setBuyer(java.lang.String Buyer) {
		set("Buyer", Buyer);
		return (M)this;
	}
	
	public java.lang.String getBuyer() {
		return getStr("Buyer");
	}

	public M setCountryOfBuyer(java.lang.String CountryOfBuyer) {
		set("CountryOfBuyer", CountryOfBuyer);
		return (M)this;
	}
	
	public java.lang.String getCountryOfBuyer() {
		return getStr("CountryOfBuyer");
	}

	public M setSeller(java.lang.String Seller) {
		set("Seller", Seller);
		return (M)this;
	}
	
	public java.lang.String getSeller() {
		return getStr("Seller");
	}

	public M setMainIndustries(java.lang.String MainIndustries) {
		set("MainIndustries", MainIndustries);
		return (M)this;
	}
	
	public java.lang.String getMainIndustries() {
		return getStr("MainIndustries");
	}

	public M setDealValueUSDmn(java.lang.String DealValueUSDmn) {
		set("DealValueUSD(mn)", DealValueUSDmn);
		return (M)this;
	}
	
	public java.lang.String getDealValueUSDmn() {
		return getStr("DealValueUSD(mn)");
	}

	public M setDealValueSource(java.lang.String DealValueSource) {
		set("DealValueSource", DealValueSource);
		return (M)this;
	}
	
	public java.lang.String getDealValueSource() {
		return getStr("DealValueSource");
	}

	public M setStakePercent(java.lang.String StakePercent) {
		set("StakePercent", StakePercent);
		return (M)this;
	}
	
	public java.lang.String getStakePercent() {
		return getStr("StakePercent");
	}

	public M setComments(java.lang.String Comments) {
		set("Comments", Comments);
		return (M)this;
	}
	
	public java.lang.String getComments() {
		return getStr("Comments");
	}

}
