package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseKeyexecutive<M extends BaseKeyexecutive<M>> extends Model<M> implements IBean {

	public M setCompanyId(java.lang.Integer CompanyId) {
		set("CompanyId", CompanyId);
		return (M)this;
	}
	
	public java.lang.Integer getCompanyId() {
		return getInt("CompanyId");
	}

	public M setKeyExecutives(java.lang.String KeyExecutives) {
		set("KeyExecutives", KeyExecutives);
		return (M)this;
	}
	
	public java.lang.String getKeyExecutives() {
		return getStr("KeyExecutives");
	}

	public M setJobTitle(java.lang.String JobTitle) {
		set("JobTitle", JobTitle);
		return (M)this;
	}
	
	public java.lang.String getJobTitle() {
		return getStr("JobTitle");
	}

}
