package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCompanybusiness<M extends BaseCompanybusiness<M>> extends Model<M> implements IBean {

	public M setCompanyId(java.lang.Integer CompanyId) {
		set("CompanyId", CompanyId);
		return (M)this;
	}
	
	public java.lang.Integer getCompanyId() {
		return getInt("CompanyId");
	}

	public M setCountry(java.lang.String Country) {
		set("Country", Country);
		return (M)this;
	}
	
	public java.lang.String getCountry() {
		return getStr("Country");
	}

	public M setCompanyName(java.lang.String CompanyName) {
		set("CompanyName", CompanyName);
		return (M)this;
	}
	
	public java.lang.String getCompanyName() {
		return getStr("CompanyName");
	}

	public M setIndustry(java.lang.String Industry) {
		set("Industry", Industry);
		return (M)this;
	}
	
	public java.lang.String getIndustry() {
		return getStr("Industry");
	}

	public M setCity(java.lang.String City) {
		set("City", City);
		return (M)this;
	}
	
	public java.lang.String getCity() {
		return getStr("City");
	}

	public M setStateCounty(java.lang.String StateCounty) {
		set("StateCounty", StateCounty);
		return (M)this;
	}
	
	public java.lang.String getStateCounty() {
		return getStr("StateCounty");
	}

	public M setKeyExecutives(java.lang.String KeyExecutives) {
		set("KeyExecutives", KeyExecutives);
		return (M)this;
	}
	
	public java.lang.String getKeyExecutives() {
		return getStr("KeyExecutives");
	}

	public M setNumberOfEmployees(java.lang.String NumberOfEmployees) {
		set("NumberOfEmployees", NumberOfEmployees);
		return (M)this;
	}
	
	public java.lang.String getNumberOfEmployees() {
		return getStr("NumberOfEmployees");
	}

	public M setEmployeeReferenceDate(java.lang.String EmployeeReferenceDate) {
		set("EmployeeReferenceDate", EmployeeReferenceDate);
		return (M)this;
	}
	
	public java.lang.String getEmployeeReferenceDate() {
		return getStr("EmployeeReferenceDate");
	}

	public M setFinancialAuditors(java.lang.String FinancialAuditors) {
		set("FinancialAuditors", FinancialAuditors);
		return (M)this;
	}
	
	public java.lang.String getFinancialAuditors() {
		return getStr("FinancialAuditors");
	}

	public M setLegalForm(java.lang.String LegalForm) {
		set("LegalForm", LegalForm);
		return (M)this;
	}
	
	public java.lang.String getLegalForm() {
		return getStr("LegalForm");
	}

	public M setListedUnlisted(java.lang.String ListedUnlisted) {
		set("ListedUnlisted", ListedUnlisted);
		return (M)this;
	}
	
	public java.lang.String getListedUnlisted() {
		return getStr("ListedUnlisted");
	}

	public M setOperationalStatus(java.lang.String OperationalStatus) {
		set("OperationalStatus", OperationalStatus);
		return (M)this;
	}
	
	public java.lang.String getOperationalStatus() {
		return getStr("OperationalStatus");
	}

	public M setISIN(java.lang.String ISIN) {
		set("ISIN", ISIN);
		return (M)this;
	}
	
	public java.lang.String getISIN() {
		return getStr("ISIN");
	}

	public M setNationalFiscalIDs(java.lang.String NationalFiscalIDs) {
		set("NationalFiscalIDs", NationalFiscalIDs);
		return (M)this;
	}
	
	public java.lang.String getNationalFiscalIDs() {
		return getStr("NationalFiscalIDs");
	}

	public M setShareholders(java.lang.String Shareholders) {
		set("Shareholders", Shareholders);
		return (M)this;
	}
	
	public java.lang.String getShareholders() {
		return getStr("Shareholders");
	}

	public M setMainProducts(java.lang.String MainProducts) {
		set("MainProducts", MainProducts);
		return (M)this;
	}
	
	public java.lang.String getMainProducts() {
		return getStr("MainProducts");
	}

	public M setPostalCode(java.lang.String PostalCode) {
		set("PostalCode", PostalCode);
		return (M)this;
	}
	
	public java.lang.String getPostalCode() {
		return getStr("PostalCode");
	}

	public M setAddress(java.lang.String Address) {
		set("Address", Address);
		return (M)this;
	}
	
	public java.lang.String getAddress() {
		return getStr("Address");
	}

	public M setPhone(java.lang.String Phone) {
		set("Phone", Phone);
		return (M)this;
	}
	
	public java.lang.String getPhone() {
		return getStr("Phone");
	}

	public M setFax(java.lang.String Fax) {
		set("Fax", Fax);
		return (M)this;
	}
	
	public java.lang.String getFax() {
		return getStr("Fax");
	}

	public M setEmail(java.lang.String Email) {
		set("Email", Email);
		return (M)this;
	}
	
	public java.lang.String getEmail() {
		return getStr("Email");
	}

	public M setWebsite(java.lang.String Website) {
		set("Website", Website);
		return (M)this;
	}
	
	public java.lang.String getWebsite() {
		return getStr("Website");
	}

	public M setAddressType(java.lang.String AddressType) {
		set("AddressType", AddressType);
		return (M)this;
	}
	
	public java.lang.String getAddressType() {
		return getStr("AddressType");
	}

	public M setBusinessDescriptionProducts(java.lang.String BusinessDescriptionProducts) {
		set("BusinessDescriptionProducts", BusinessDescriptionProducts);
		return (M)this;
	}
	
	public java.lang.String getBusinessDescriptionProducts() {
		return getStr("BusinessDescriptionProducts");
	}

	public M setImport(java.lang.String Import) {
		set("Import", Import);
		return (M)this;
	}
	
	public java.lang.String getImport() {
		return getStr("Import");
	}

	public M setExport(java.lang.String Export) {
		set("Export", Export);
		return (M)this;
	}
	
	public java.lang.String getExport() {
		return getStr("Export");
	}

	public M setIncorporationDate(java.lang.String IncorporationDate) {
		set("IncorporationDate", IncorporationDate);
		return (M)this;
	}
	
	public java.lang.String getIncorporationDate() {
		return getStr("IncorporationDate");
	}

	public M setSource(java.lang.String Source) {
		set("Source", Source);
		return (M)this;
	}
	
	public java.lang.String getSource() {
		return getStr("Source");
	}

	public M setEMISID(java.lang.String EMISID) {
		set("EMISID", EMISID);
		return (M)this;
	}
	
	public java.lang.String getEMISID() {
		return getStr("EMISID");
	}

	public M setTotaloperatingrevenue(java.lang.String Totaloperatingrevenue) {
		set("Totaloperatingrevenue", Totaloperatingrevenue);
		return (M)this;
	}
	
	public java.lang.String getTotaloperatingrevenue() {
		return getStr("Totaloperatingrevenue");
	}

	public M setFiscalYear(java.lang.String FiscalYear) {
		set("FiscalYear", FiscalYear);
		return (M)this;
	}
	
	public java.lang.String getFiscalYear() {
		return getStr("FiscalYear");
	}

	public M setAudited(java.lang.String Audited) {
		set("Audited", Audited);
		return (M)this;
	}
	
	public java.lang.String getAudited() {
		return getStr("Audited");
	}

	public M setConsolidated(java.lang.String Consolidated) {
		set("Consolidated", Consolidated);
		return (M)this;
	}
	
	public java.lang.String getConsolidated() {
		return getStr("Consolidated");
	}

	public M setF35(java.lang.String F35) {
		set("F35", F35);
		return (M)this;
	}
	
	public java.lang.String getF35() {
		return getStr("F35");
	}

}
